server:
  port: 8081

spring:
  application:
    name: sc-gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
        - id: service-hi
          uri: lb://SERVICE-HI
          predicates:
            - Path=/demo/**
          filters:
            - StripPrefix=1
            - RequestTime=true
        - id: service-hello
          uri: lb://SERVICE-HELLO
          predicates:
            - Path=/demo2/**
          filters:
            - StripPrefix=1
            - RequestTime=true
        - id: sc-gateway-server
          uri: lb://SC-GATEWAY-SERVER
          predicates:
            - Path=/demo3/**
          filters:
            - StripPrefix=1
            - RequestTime=true
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@hostAddrKeyResolver}'
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 10
        - id: service-feign
          uri: lb://SERVICE-FEIGN
          predicates:
            - Path=/demo4/**
          filters:
            - StripPrefix=1
            - RequestTime=true
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@hostAddrKeyResolver}'
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 10
      # 公共熔断设置
      default-filters:
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/fallback
#        以下是过滤器--没有敲，先写上备注【依赖redis】【注意：网上说在default-filters配置有坑，可以尝试在每个filters都配置一下】----验证过-----不行
#        - name: RequestRateLimiter
#          args:
#            key-resolver: '#{@hostAddrKeyResolver}'
#            redis-rate-limiter.replenishRate: 1
#            redis-rate-limiter.burstCapacity: 5
#  redis配置
  redis:
    host: 47.98.119.18
    port: 9999
    database: 0
    password: 123456

# 公共熔断设置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug



